export const CountriesData = [
    { label: "Afghanistan", value: "Afghanistan" },
    { label: "Albania", value: "Albania" },
    { label: "Algeria", value: "Algeria" },
    { label: "Andorra", value: "Andorra" },
    { label: "Angola", value: "Angola" },
    { label: "Antigua and Barbuda", value: "Antigua and Barbuda" },
    { label: "Argentina", value: "Argentina" },
    { label: "Armenia", value: "Armenia" },
    { label: "Australia", value: "Australia" },
    { label: "Austria", value: "Austria" },
    { label: "Azerbaijan", value: "Azerbaijan" },
    { label: "Bahamas", value: "Bahamas" },
    { label: "Bahrain", value: "Bahrain" },
    { label: "Bangladesh", value: "Bangladesh" },
    { label: "Barbados", value: "Barbados" },
    { label: "Belarus", value: "Belarus" },
    { label: "Belgium", value: "Belgium" },
    { label: "Belize", value: "Belize" },
    { label: "Benin", value: "Benin" },
    { label: "Bhutan", value: "Bhutan" },
    { label: "Bolivia", value: "Bolivia" },
    { label: "Bosnia and Herzegovina", value: "Bosnia and Herzegovina" },
    { label: "Botswana", value: "Botswana" },
    { label: "Brazil", value: "Brazil" },
    { label: "Brunei", value: "Brunei" },
    { label: "Bulgaria", value: "Bulgaria" },
    { label: "Burkina Faso", value: "Burkina Faso" },
    { label: "Burundi", value: "Burundi" },
    { label: "Cabo Verde", value: "Cabo Verde" },
    { label: "Cambodia", value: "Cambodia" },
    { label: "Cameroon", value: "Cameroon" },
    { label: "Canada", value: "Canada" },
    { label: "Central African Republic", value: "Central African Republic" },
    { label: "Chad", value: "Chad" },
    { label: "Chile", value: "Chile" },
    { label: "China", value: "China" },
    { label: "Colombia", value: "Colombia" },
    { label: "Comoros", value: "Comoros" },
    { label: "Congo (Congo-Brazzaville)", value: "Congo (Congo-Brazzaville)" },
    { label: "Congo (Democratic Republic)", value: "Congo (Democratic Republic)" },
    { label: "Costa Rica", value: "Costa Rica" },
    { label: "Croatia", value: "Croatia" },
    { label: "Cuba", value: "Cuba" },
    { label: "Cyprus", value: "Cyprus" },
    { label: "Czech Republic", value: "Czech Republic" },
    { label: "Denmark", value: "Denmark" },
    { label: "Djibouti", value: "Djibouti" },
    { label: "Dominica", value: "Dominica" },
    { label: "Dominican Republic", value: "Dominican Republic" },
    { label: "Ecuador", value: "Ecuador" },
    { label: "Egypt", value: "Egypt" },
    { label: "El Salvador", value: "El Salvador" },
    { label: "Equatorial Guinea", value: "Equatorial Guinea" },
    { label: "Eritrea", value: "Eritrea" },
    { label: "Estonia", value: "Estonia" },
    { label: "Eswatini", value: "Eswatini" },
    { label: "Ethiopia", value: "Ethiopia" },
    { label: "Fiji", value: "Fiji" },
    { label: "Finland", value: "Finland" },
    { label: "France", value: "France" },
    { label: "Gabon", value: "Gabon" },
    { label: "Gambia", value: "Gambia" },
    { label: "Georgia", value: "Georgia" },
    { label: "Germany", value: "Germany" },
    { label: "Ghana", value: "Ghana" },
    { label: "Greece", value: "Greece" },
    { label: "Grenada", value: "Grenada" },
    { label: "Guatemala", value: "Guatemala" },
    { label: "Guinea", value: "Guinea" },
    { label: "Guinea-Bissau", value: "Guinea-Bissau" },
    { label: "Guyana", value: "Guyana" },
    { label: "Haiti", value: "Haiti" },
    { label: "Honduras", value: "Honduras" },
    { label: "Hungary", value: "Hungary" },
    { label: "Iceland", value: "Iceland" },
    { label: "India", value: "India" },
    { label: "Indonesia", value: "Indonesia" },
    { label: "Iran", value: "Iran" },
    { label: "Iraq", value: "Iraq" },
    { label: "Ireland", value: "Ireland" },
    { label: "Israel", value: "Israel" },
    { label: "Italy", value: "Italy" },
    { label: "Jamaica", value: "Jamaica" },
    { label: "Japan", value: "Japan" },
    { label: "Jordan", value: "Jordan" },
    { label: "Kazakhstan", value: "Kazakhstan" },
    { label: "Kenya", value: "Kenya" },
    { label: "Kiribati", value: "Kiribati" },
    { label: "Kuwait", value: "Kuwait" },
    { label: "Kyrgyzstan", value: "Kyrgyzstan" },
    { label: "Laos", value: "Laos" },
    { label: "Latvia", value: "Latvia" },
    { label: "Lebanon", value: "Lebanon" },
    { label: "Lesotho", value: "Lesotho" },
    { label: "Liberia", value: "Liberia" },
    { label: "Libya", value: "Libya" },
    { label: "Liechtenstein", value: "Liechtenstein" },
    { label: "Lithuania", value: "Lithuania" },
    { label: "Luxembourg", value: "Luxembourg" },
    { label: "Madagascar", value: "Madagascar" },
    { label: "Malawi", value: "Malawi" },
    { label: "Malaysia", value: "Malaysia" },
    { label: "Maldives", value: "Maldives" },
    { label: "Mali", value: "Mali" },
    { label: "Malta", value: "Malta" },
    { label: "Marshall Islands", value: "Marshall Islands" },
    { label: "Mauritania", value: "Mauritania" },
    { label: "Mauritius", value: "Mauritius" },
    { label: "Mexico", value: "Mexico" },
    { label: "Micronesia", value: "Micronesia" },
    { label: "Moldova", value: "Moldova" },
    { label: "Monaco", value: "Monaco" },
    { label: "Mongolia", value: "Mongolia" },
    { label: "Montenegro", value: "Montenegro" },
    { label: "Morocco", value: "Morocco" },
    { label: "Mozambique", value: "Mozambique" },
    { label: "Myanmar (Burma)", value: "Myanmar (Burma)" },
    { label: "Namibia", value: "Namibia" },
    { label: "Nauru", value: "Nauru" },
    { label: "Nepal", value: "Nepal" },
    { label: "Netherlands", value: "Netherlands" },
    { label: "New Zealand", value: "New Zealand" },
    { label: "Nicaragua", value: "Nicaragua" },
    { label: "Niger", value: "Niger" },
    { label: "Nigeria", value: "Nigeria" },
    { label: "North Korea", value: "North Korea" },
    { label: "North Macedonia", value: "North Macedonia" },
    { label: "Norway", value: "Norway" },
    { label: "Oman", value: "Oman" },
    { label: "Pakistan", value: "Pakistan" },
    { label: "Palau", value: "Palau" },
    { label: "Palestine", value: "Palestine" },
    { label: "Panama", value: "Panama" },
    { label: "Papua New Guinea", value: "Papua New Guinea" },
    { label: "Paraguay", value: "Paraguay" },
    { label: "Peru", value: "Peru" },
    { label: "Philippines", value: "Philippines" },
    { label: "Poland", value: "Poland" },
    { label: "Portugal", value: "Portugal" },
    { label: "Qatar", value: "Qatar" },
    { label: "Romania", value: "Romania" },
    { label: "Russia", value: "Russia" },
    { label: "Rwanda", value: "Rwanda" },
    { label: "Saint Kitts and Nevis", value: "Saint Kitts and Nevis" },
    { label: "Saint Lucia", value: "Saint Lucia" },
    { label: "Saint Vincent and the Grenadines", value: "Saint Vincent and the Grenadines" },
    { label: "Samoa", value: "Samoa" },
    { label: "San Marino", value: "San Marino" },
    { label: "Sao Tome and Principe", value: "Sao Tome and Principe" },
    { label: "Saudi Arabia", value: "Saudi Arabia" },
    { label: "Senegal", value: "Senegal" },
    { label: "Serbia", value: "Serbia" },
    { label: "Seychelles", value: "Seychelles" },
    { label: "Sierra Leone", value: "Sierra Leone" },
    { label: "Singapore", value: "Singapore" },
    { label: "Slovakia", value: "Slovakia" },
    { label: "Slovenia", value: "Slovenia" },
    { label: "Solomon Islands", value: "Solomon Islands" },
    { label: "Somalia", value: "Somalia" },
    { label: "South Africa", value: "South Africa" },
    { label: "South Korea", value: "South Korea" },
    { label: "South Sudan", value: "South Sudan" },
    { label: "Spain", value: "Spain" },
    { label: "Sri Lanka", value: "Sri Lanka" },
    { label: "Sudan", value: "Sudan" },
    { label: "Suriname", value: "Suriname" },
    { label: "Sweden", value: "Sweden" },
    { label: "Switzerland", value: "Switzerland" },
    { label: "Syria", value: "Syria" },
    { label: "Taiwan", value: "Taiwan" },
    { label: "Tajikistan", value: "Tajikistan" },
    { label: "Tanzania", value: "Tanzania" },
    { label: "Thailand", value: "Thailand" },
    { label: "Timor-Leste", value: "Timor-Leste" },
    { label: "Togo", value: "Togo" },
    { label: "Tonga", value: "Tonga" },
    { label: "Trinidad and Tobago", value: "Trinidad and Tobago" },
    { label: "Tunisia", value: "Tunisia" },
    { label: "Turkey", value: "Turkey" },
    { label: "Turkmenistan", value: "Turkmenistan" },
    { label: "Tuvalu", value: "Tuvalu" },
    { label: "Uganda", value: "Uganda" },
    { label: "Ukraine", value: "Ukraine" },
    { label: "United Arab Emirates", value: "United Arab Emirates" },
    { label: "United Kingdom", value: "United Kingdom" },
    { label: "United States", value: "United States" },
    { label: "Uruguay", value: "Uruguay" },
    { label: "Uzbekistan", value: "Uzbekistan" },
    { label: "Vanuatu", value: "Vanuatu" },
    { label: "Vatican City", value: "Vatican City" },
    { label: "Venezuela", value: "Venezuela" },
    { label: "Vietnam", value: "Vietnam" },
    { label: "Yemen", value: "Yemen" },
    { label: "Zambia", value: "Zambia" },
    { label: "Zimbabwe", value: "Zimbabwe" }
];


export const BusinessNature = [
    { label: "Accelerators", value: "Accelerators" },
    { label: "Adhesives & Paints", value: "Adhesives & Paints" },
    { label: "Aerospace", value: "Aerospace" },
    { label: "Agriculture", value: "Agriculture" },
    { label: "Agriculture and Agribusiness", value: "Agriculture and Agribusiness" },
    { label: "Architecture & Design", value: "Architecture & Design" },
    { label: "Artificial Intelligence", value: "Artificial Intelligence" },
    { label: "Arts and Culture", value: "Arts and Culture" },
    { label: "Associations and Federations", value: "Associations and Federations" },
    { label: "Automotive", value: "Automotive" },
    { label: "Automotive Glass", value: "Automotive Glass" },
    { label: "Aviation", value: "Aviation" },
    { label: "Banks and Other Financial Institutions", value: "Banks and Other Financial Institutions" },
    { label: "Beveled Glass", value: "Beveled Glass" },
    { label: "Building Materials", value: "Building Materials" },
    { label: "Business Council", value: "Business Council" },
    { label: "Chambers of Commerce and Industry", value: "Chambers of Commerce and Industry" },
    { label: "Chemical Industry", value: "Chemical Industry" },
    { label: "Coloured and Pure Glass", value: "Coloured and Pure Glass" },
    { label: "Commerce", value: "Commerce" },
    { label: "Conglomerate", value: "Conglomerate" },
    { label: "Construction and Engineering", value: "Construction and Engineering" },
    { label: "Consultancy", value: "Consultancy" },
    { label: "Consumer Goods", value: "Consumer Goods" },
    { label: "Contracting", value: "Contracting" },
    { label: "Corporate", value: "Corporate" },
    { label: "Cosmetics", value: "Cosmetics" },
    { label: "Decor Glass", value: "Decor Glass" },
    { label: "Defense/Military", value: "Defense/Military" },
    { label: "Digital Solution", value: "Digital Solution" },
    { label: "Diplomatic Mission", value: "Diplomatic Mission" },
    { label: "Dust Control & Vacuum Cleaners", value: "Dust Control & Vacuum Cleaners" },
    { label: "Economic Development", value: "Economic Development" },
    { label: "Education", value: "Education" },
    { label: "Energy and Mining", value: "Energy and Mining" },
    { label: "Event Organizer", value: "Event Organizer" },
    { label: "Facades and Cabins", value: "Facades and Cabins" },
    { label: "Facilities Management", value: "Facilities Management" },
    { label: "Fiber Glass", value: "Fiber Glass" },
    { label: "Fishery", value: "Fishery" },
    { label: "Flat Glass", value: "Flat Glass" },
    { label: "Flooring", value: "Flooring" },
    { label: "Food & Beverages", value: "Food & Beverages" },
    { label: "Foreign Affairs", value: "Foreign Affairs" },
    { label: "Furniture Manufacturers", value: "Furniture Manufacturers" },
    { label: "Glass Machinery", value: "Glass Machinery" },
    { label: "Glass Manufacturing", value: "Glass Manufacturing" },
    { label: "Government", value: "Government" },
    { label: "Government Department", value: "Government Department" },
    { label: "Government Programs and Initiatives", value: "Government Programs and Initiatives" },
    { label: "Green Technology and Climate Change", value: "Green Technology and Climate Change" },
    { label: "Hand Craft", value: "Hand Craft" },
    { label: "Handrail", value: "Handrail" },
    { label: "Healthcare and Pharmaceutical", value: "Healthcare and Pharmaceutical" },
    { label: "Heat Treated Glass", value: "Heat Treated Glass" },
    { label: "Hospitality", value: "Hospitality" },
    { label: "Immigration Service", value: "Immigration Service" },
    { label: "Incubators", value: "Incubators" },
    { label: "Infrastructure", value: "Infrastructure" },
    { label: "Insurance", value: "Insurance" },
    { label: "Inter-governmental organizations (IGOs)", value: "Inter-governmental organizations (IGOs)" },
    { label: "Investment & Trade", value: "Investment & Trade" },
    { label: "Investment and Freezones", value: "Investment and Freezones" },
    { label: "Investment Firm", value: "Investment Firm" },
    { label: "Investment Promotion Agency", value: "Investment Promotion Agency" },
    { label: "Investor", value: "Investor" },
    { label: "IT/ ICT and Telecommunication", value: "IT/ ICT and Telecommunication" },
    { label: "Law and Legal Affairs", value: "Law and Legal Affairs" },
    { label: "Life Sciences", value: "Life Sciences" },
    { label: "Lightning", value: "Lightning" },
    { label: "Local Government Units", value: "Local Government Units" },
    { label: "Logistics and Transportation", value: "Logistics and Transportation" },
    { label: "Luxury Goods & Jewelry", value: "Luxury Goods & Jewelry" },
    { label: "Management & Investment", value: "Management & Investment" },
    { label: "Manufacturing", value: "Manufacturing" },
    { label: "Maritime", value: "Maritime" },
    { label: "Marketing", value: "Marketing" },
    { label: "Marketing and Advertising", value: "Marketing and Advertising" },
    { label: "MDF/ Panels and Laminates", value: "MDF/ Panels and Laminates" },
    { label: "Media", value: "Media" },
    { label: "Ministries", value: "Ministries" },
    { label: "Non-Profit Organizations", value: "Non-Profit Organizations" },
    { label: "Oil and Gas", value: "Oil and Gas" },
    { label: "Others", value: "Others" },
    { label: "Paper Industry", value: "Paper Industry" },
    { label: "Partitions Skylights", value: "Partitions Skylights" },
    { label: "Pharmaceutical Glass", value: "Pharmaceutical Glass" },
    { label: "Plastics", value: "Plastics" },
    { label: "Plywood/ Hardboard Decorative", value: "Plywood/ Hardboard Decorative" },
    { label: "Private Equity", value: "Private Equity" },
    { label: "Private Sector", value: "Private Sector" },
    { label: "Professional Services", value: "Professional Services" },
    { label: "Property Development", value: "Property Development" },
    { label: "Property Portal", value: "Property Portal" },
    { label: "Property Valuation", value: "Property Valuation" },
    { label: "Protective Glass", value: "Protective Glass" },
    { label: "Publishing House", value: "Publishing House" },
    { label: "Pyrex Glass", value: "Pyrex Glass" },
    { label: "Raw Materials", value: "Raw Materials" },
    { label: "Real Estate", value: "Real Estate" },
    { label: "Real Estate Brokers", value: "Real Estate Brokers" },
    { label: "Regional Organizations", value: "Regional Organizations" },
    { label: "Retail", value: "Retail" },
    { label: "Robotics", value: "Robotics" },
    { label: "Security", value: "Security" },
    { label: "Shipbuilding", value: "Shipbuilding" },
    { label: "Shock Resistant Glass", value: "Shock Resistant Glass" },
    { label: "Smart Solutions", value: "Smart Solutions" },
    { label: "Software", value: "Software" },
    { label: "Sovereign Wealth Funds", value: "Sovereign Wealth Funds" },
    { label: "Special Economic Zones", value: "Special Economic Zones" },
    { label: "Spider Glass", value: "Spider Glass" },
    { label: "Sports and Recreation", value: "Sports and Recreation" },
    { label: "Startups", value: "Startups" },
    { label: "Supermarket", value: "Supermarket" },
    { label: "Supplier", value: "Supplier" },
    { label: "Table Wear", value: "Table Wear" },
    { label: "Technology", value: "Technology" },
    { label: "Textile and Apparel", value: "Textile and Apparel" },
    { label: "Timber/ Hardwood & Softwood", value: "Timber/ Hardwood & Softwood" },
    { label: "Tools & Cutting Machines", value: "Tools & Cutting Machines" },
    { label: "Tourism", value: "Tourism" },
    { label: "Trade Promotion Organizations", value: "Trade Promotion Organizations" },
    { label: "Training & Employment", value: "Training & Employment" },
    { label: "Transport", value: "Transport" },
    { label: "Transport, Logistics & Supply Chain", value: "Transport, Logistics & Supply Chain" },
    { label: "Urban & City Development", value: "Urban & City Development" },
    { label: "Venture Capital", value: "Venture Capital" },
    { label: "Warehousing", value: "Warehousing" },
    { label: "Waste Management", value: "Waste Management" },
    { label: "Water and Sanitation", value: "Water and Sanitation" },
    { label: "Water Bottling and Water Treatment", value: "Water Bottling and Water Treatment" },
    { label: "Windshield Glass", value: "Windshield Glass" },
    { label: "Wood", value: "Wood" },
    { label: "Wood Flooring", value: "Wood Flooring" }
];